import type { Metadata } from 'next'
import { font } from '../lib/config/font'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: 'https://github.com/jvxz.png',
  },
}

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`
      ${font.mono.variable}
      ${font.sans.variable}
      `}
      >
        {children}
      </body>
    </html>
  )
}
